### PR TITLE
Revert "Laravel 5 branch"

### PR DESCRIPTION
**Pull request by stokic**
this needs to be merged in a separate branch because of backwards compatibility with L4 which most projects still use...

### CODE REVIEW

**Comment by hisorange** [comment]
Version 1.* now is closed and supports only Laravel 4.
Version 2.* begins with the PR from before and support moved to Laravel 5.
As long as peeps do not use 'dev-master' pulls for their L4, there should be no issue.

**Comment by stokic** [comment]
Awesome, thanks!

**Comment by hisorange** [comment]
No, thanks for the PR. I am so far away from Laravel atm I could not handle the update without it.

**Comment by stokic** [comment]
You're welcome :)

**Pull request closed without merging**
